
--- EJEMPLO DE WHERE
SELECT * 
    FROM HR.employees
WHERE JOB_ID = 'IT_PROG';

-- = IGUAL  > MAYOR < MENOR >= MAYOR IGUAL <= MENOR IGUAL <> != DISTINTO
SELECT * 
    FROM HR.employees
WHERE SALARY >= 10000;

-- AND   OR
SELECT * 
    FROM HR.employees
WHERE JOB_ID = 'IT_PROG' AND SALARY > 8000;

-- AND   OR
SELECT * 
    FROM HR.employees
WHERE JOB_ID = 'IT_PROG' AND SALARY > 4500 AND HIRE_DATE > TO_DATE('31/12/2005','DD/MM/YYYY')

SELECT * 
    FROM HR.employees
WHERE JOB_ID = 'IT_PROG' OR JOB_ID  = 'FI_ACCOUNT' OR SALARY > 10000;



