--- AGREGAR (ADD) CAMPOS TABLA - (ALTER TABLE)

CREATE TABLE ESTUDIANTES (
    ID NUMBER(4),
    NOMBRE VARCHAR2(20)
);

INSERT INTO ESTUDIANTES VALUES (1,'Josue');
INSERT INTO ESTUDIANTES VALUES (2,'Luis','Gonzalez');

SELECT * FROM ESTUDIANTES;

ALTER TABLE ESTUDIANTES ADD APELLIDO VARCHAR2(50);

ALTER TABLE ESTUDIANTES ADD EDAD NUMBER(10) DEFAULT 0 NOT NULL;
ALTER TABLE ESTUDIANTES MODIFY NOMBRE VARCHAR2(50);


DESC ESTUDIANTES;

ALTER TABLE ESTUDIANTES ADD GENERO CHAR;
ALTER TABLE ESTUDIANTES DROP COLUMN GENERO;


ALTER TABLE ESTUDIANTES ADD CONSTRAINT CK_GENERO CHECK (GENERO = 'M' OR GENERO= 'F');

INSERT INTO ESTUDIANTES VALUES (4,'Jason','Montenegro',23,'M');

SELECT * FROM ESTUDIANTES

--SUBCONSULTA

SELECT FIRST_NAME, LAST_NAME
FROM HR.employees
WHERE EMPLOYEE_ID IN (
            SELECT EMPLOYEE_ID
            FROM HR.job_history
            GROUP BY EMPLOYEE_ID
            HAVING COUNT(*) > 1
            )
-- VISTA             

CREATE OR REPLACE VIEW VW_EMP_DOS_CONTRATOS AS
    SELECT FIRST_NAME, LAST_NAME, EMAIL, EMPLOYEE_ID
    FROM HR.employees
    WHERE EMPLOYEE_ID IN (
                SELECT EMPLOYEE_ID
                FROM HR.job_history
                GROUP BY EMPLOYEE_ID
                HAVING COUNT(*) > 1
                )
   ORDER BY LAST_NAME DESC;
                
                
SELECT * FROM VW_EMP_DOS_CONTRATOS                

SELECT FIRST_NAME FROM VW_EMP_DOS_CONTRATOS   
WHERE FIRST_NAME LIKE 'J%'

DESC HR.employees

DROP VIEW VW_EMP_DOS_CONTRATOS;

CREATE VIEW VW_EMPLEADOS_SALARIOS AS
SELECT e.first_name, e.salary, j.min_salary, j.max_salary
FROM HR.employees e INNER JOIN HR.jobs j
ON e.job_id = j.job_id
;

SELECT * FROM VW_EMPLEADOS_SALARIOS


--PROCEDIMIENTOS

-- PROCEDIMIENTOS ALMACENADOS
DESC PRODUCTO
DROP TABLE PRODUCTO

CREATE TABLE PRODUCTO (
    ID NUMBER(4),
    NOMBRE VARCHAR2(20),
    PRECIO NUMBER(6,2)
);

INSERT INTO PRODUCTO VALUES (1,'Mouse',50.20);
INSERT INTO PRODUCTO VALUES (2,'Monitores',1000);
INSERT INTO PRODUCTO VALUES (3,'Silla',700.50);
INSERT INTO PRODUCTO VALUES (4,'Telcado',40);
INSERT INTO PRODUCTO VALUES (5,'WebCam',300);

CREATE VIEW VW_PRODUCTOS_CALCULADORS AS 
    SELECT P.*, PRECIO * 0.05 AS PORCENTAJE, PRECIO + PRECIO * 0.05 AS TOTAL_CALC
    FROM PRODUCTO P
;

SELECT * FROM VW_PRODUCTOS_CALCULADORS

UPDATE PRODUDCTO SET PRECIO = PRECIO + PRECIO * 0.05;

DROP PROCEDURE PA_AUMENTA_PRECIO

CREATE PROCEDURE PA_AUMENTA_PRECIO
AS
    BEGIN
        UPDATE PRODUCTO SET PRECIO = PRECIO + PRECIO * 0.05;
    END;

    
    EXECUTE PA_AUMENTA_PRECIO;
