/*
    DROP TABLE DETALLEPEDIDOS;
    DROP TABLE PRODUCTOS;
    DROP TABLE PEDIDOS;
    DROP TABLE GAMASPRODUCTOS;
    DROP TABLE PAGOS;  
    DROP TABLE CLIENTES;
    DROP TABLE EMPLEADOS;    
    DROP TABLE OFICINAS; 
*/

SELECT * FROM DETALLEPEDIDOS;
SELECT * FROM PRODUCTOS;
SELECT * FROM PEDIDOS;
SELECT * FROM GAMASPRODUCTOS;
SELECT * FROM PAGOS;
SELECT * FROM CLIENTES;
SELECT * FROM EMPLEADOS;
SELECT * FROM OFICINAS;

SELECT * FROM CLIENTES;

--CONSULTA 5

SELECT COUNT (*) AS "CLIENTES_NORTEAMERICANOS"
FROM CLIENTES
WHERE PAIS = 'USA';

--CONSULTA 6

SELECT PAIS, COUNT (*) AS "CLIENTES_PAIS"
FROM CLIENTES
GROUP BY PAIS;

--CONSULTA 7

SELECT * FROM CLIENTES;
SELECT * FROM EMPLEADOS;

SELECT NOMBRECLIENTE AS "NOMBRE CLIENTE", CODIGOEMPLEADOREPVENTAS AS "NOMBRE REPRESENTANTE"
FROM CLIENTES C, EMPLEADOS E
WHERE c.codigoempleadorepventas = e.codigoempleado;

--CONSULTA 8

SELECT * FROM PAGOS;
SELECT * FROM CLIENTES;
      
      SELECT DISTINCT C.NOMBRECLIENTE
      FROM CLIENTES C, PAGOS P
      WHERE P.CODIGOCLIENTE = C.CODIGOCLIENTE AND p.fechapago LIKE '%/07';
